trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  projectFolder: '$(Build.SourcesDirectory)'
  outputFolder: '$(Build.ArtifactStagingDirectory)\Packages'
  orchestratorConnection: 'UiPath-Orchestrator'
  orchestratorFolder: 'Comercio\Cartera'

steps:
- task: UiPathPack@3
  displayName: 'Pack UiPath project'
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(projectFolder)\project.json'
    outputPath: '$(outputFolder)'
    outputType: 'Process'
    orchestratorConnection: '$(orchestratorConnection)'
    traceLevel: 'Information'

- task: UiPathDeploy@3
  displayName: 'Deploy package to Orchestrator'
  inputs:
    orchestratorConnection: '$(orchestratorConnection)'
    packagesPath: '$(outputFolder)'
    folderName: '$(orchestratorFolder)'
    traceLevel: 'Information'


