trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  projectFolder: '$(Build.SourcesDirectory)'
  outputFolder: '$(Build.ArtifactStagingDirectory)\Packages'
  orchestratorConnection: 'UiPath-Orchestrator'
  orchestratorFolder: 'Comercio\Cartera'

steps:
- task: PowerShell@2
  displayName: 'Import assets to new Orchestrator account'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/orchestrator/scripts/import-assets.ps1'
    pwsh: false
  env:
    UIPATH_ORG: $(UIPATH_ORG)
    UIPATH_TENANT: $(UIPATH_TENANT)
    UIPATH_CLIENT_ID: $(UIPATH_CLIENT_ID)
    UIPATH_CLIENT_SECRET: $(UIPATH_CLIENT_SECRET)
    UIPATH_FOLDER_ID: $(UIPATH_FOLDER_ID)


